Livraria/HBsis/HBsis.Livraria/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HBsis.Livraria.Domain.Entidades;
using Hbsis.Livraria.Dominio;

namespace HBsis.Livraria.Controllers
{
    public class AutorController : Controller
    {
        private LivrariaContext db = new LivrariaContext();

        // GET: Autor
        public ActionResult Index()
        {
            var autor = db.Autor.OrderBy(a => a.Nome);
            return View(autor.ToList());
        }

        // GET: Autor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autor.Find(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // GET: Autor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Autor/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Autor.Add(autor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(autor);
        }

        // GET: Autor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autor.Find(id);
            if (autor == null)
            {
                return HttpNotFound();
            }
            return View(autor);
        }

        // POST: Autor/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome")] Autor autor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(autor);
        }

        // GET: Autor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Autor autor = db.Autor.Find(id);
            if (autor == null)
            {
                return HttpNotFound();
            }

            int qtdLivros = db.Livros.Where(l => l.Autor_ID == id).Count();
            ViewBag.possuiDependencia = false;
            if (qtdLivros != 0)
            {
                ViewBag.possuiDependencia = true;
            }

            return View(autor);
        }

        // POST: Autor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Autor autor = db.Autor.Find(id);
            db.Autor.Remove(autor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Livraria/HBsis/HBsis.Livraria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HBsis.Livraria.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Livraria/HBsis/HBsis.Livraria/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HBsis.Livraria.Domain.Entidades;
using Hbsis.Livraria.Dominio;

namespace HBsis.Livraria.Controllers
{
    public class LivrosController : Controller
    {
        private LivrariaContext db = new LivrariaContext();

        // GET: Livros
        public ActionResult Index()
        {
            var livros = db.Livros.Include(l => l.Autor).OrderBy(l => l.Nome);
            return View(livros.ToList());
        }

        // GET: Livros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livros livros = db.Livros.Include(l => l.Autor).Where(l => l.ID == id).FirstOrDefault();
            if (livros == null)
            {
                return HttpNotFound();
            }
            return View(livros);
        }

        // GET: Livros/Create
        public ActionResult Create()
        {
            ViewBag.Autor_ID = new SelectList(db.Autor, "ID", "Nome");
            return View();
        }

        // POST: Livros/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,Autor_ID,Descricao,DataPublicacao")] Livros livros)
        {
            if (ModelState.IsValid)
            {
                db.Livros.Add(livros);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Autor_ID = new SelectList(db.Autor, "ID", "Nome", livros.Autor_ID);
            return View(livros);
        }

        // GET: Livros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livros livros = db.Livros.Include(l => l.Autor).Where(l => l.ID == id).FirstOrDefault();
            if (livros == null)
            {
                return HttpNotFound();
            }
            ViewBag.Autor_ID = new SelectList(db.Autor, "ID", "Nome", livros.Autor_ID);
            return View(livros);
        }

        // POST: Livros/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,Autor_ID,Descricao,DataPublicacao")] Livros livros)
        {
            if (ModelState.IsValid)
            {
                db.Entry(livros).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Autor_ID = new SelectList(db.Autor, "ID", "Nome", livros.Autor_ID);
            return View(livros);
        }

        // GET: Livros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Livros livros = db.Livros.Include(l => l.Autor).Where(l => l.ID == id).FirstOrDefault();
            if (livros == null)
            {
                return HttpNotFound();
            }
            return View(livros);
        }

        // POST: Livros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Livros livros = db.Livros.Find(id);
            db.Livros.Remove(livros);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Livraria/HBsis/HBsis.Livraria/Views/Autor/Create.cshtml
@model HBsis.Livraria.Domain.Entidades.Autor

@{
    ViewBag.Title = "Novo";
}

<h2>Novo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Livraria/HBsis/HBsis.Livraria/Views/Autor/Delete.cshtml
@model HBsis.Livraria.Domain.Entidades.Autor

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>
<div>
    <h4>Autor</h4>
    @if (!ViewBag.possuiDependencia)
    {
        <h3>Você tem certeza que deseja remover o registro?</h3>
    }
    else
    {
        <h3 class="text-danger">Não é possível excluir este autor pois ele possui livros cadastrados.</h3>
    }
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @if (!ViewBag.possuiDependencia)
            {
                <input type="submit" value="Excluir" class="btn btn-default" />
            }
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Livraria/HBsis/HBsis.Livraria/Views/Autor/Details.cshtml
@model HBsis.Livraria.Domain.Entidades.Autor

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Autor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Livraria/HBsis/HBsis.Livraria/Views/Autor/Edit.cshtml
@model HBsis.Livraria.Domain.Entidades.Autor

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Autor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Livraria/HBsis/HBsis.Livraria/Views/Autor/Index.cshtml
@model IEnumerable<HBsis.Livraria.Domain.Entidades.Autor>

@{
    ViewBag.Title = "Autor";
}

<h2>Autores</h2>

<p>
    @Html.ActionLink("Adicionar novo autor", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.ID }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Livraria/HBsis/HBsis.Livraria/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Aqui estão as informações da página "Sobre".</p>
<p>Lorem ipsum dolor sit amet.</p>

Livraria/HBsis/HBsis.Livraria/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Suporte:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Livraria/HBsis/HBsis.Livraria/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Livraria";
}

<div class="jumbotron">
    <h1>Sistema de Gestão de Livraria</h1>
    <p class="lead">Bem vindo ao sistema de gestão de Livraria</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Livros</h2>
        <p>
           Clique aqui para acessar a tela de cadastro e gerenciamento de livros!
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Livros")">Acessar &raquo;</a></p>
    </div>

    <div class="col-md-6">
        <h2>Autores</h2>
        <p>
            Clique aqui para acessar a tela de cadastro e gerenciamento de autores!
        </p>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Autor")">Acessar &raquo;</a></p>
    </div>
</div>

Livraria/HBsis/HBsis.Livraria/Views/Livros/Create.cshtml
@model HBsis.Livraria.Domain.Entidades.Livros

@{
    ViewBag.Title = "Novo";
}

<h2>Novo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Livro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autor_ID, "Autor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Autor_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Autor_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataPublicacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataPublicacao, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DataPublicacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Livraria/HBsis/HBsis.Livraria/Views/Livros/Delete.cshtml
@model HBsis.Livraria.Domain.Entidades.Livros

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<div>
    <h4>Livros</h4>
    <h3>Você tem certeza que deseja remover o registro?</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autor.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataPublicacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataPublicacao)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" />
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Livraria/HBsis/HBsis.Livraria/Views/Livros/Details.cshtml
@model HBsis.Livraria.Domain.Entidades.Livros

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Livros</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autor.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataPublicacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataPublicacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Livraria/HBsis/HBsis.Livraria/Views/Livros/Edit.cshtml
@model HBsis.Livraria.Domain.Entidades.Livros
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Livros</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Autor_ID, "Autor_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Autor_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Autor_ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DataPublicacao, htmlAttributes: new { @class = "control-label col-md-2 " })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataPublicacao, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.DataPublicacao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Livraria/HBsis/HBsis.Livraria/Views/Livros/Index.cshtml
@model IEnumerable<HBsis.Livraria.Domain.Entidades.Livros>

@{
    ViewBag.Title = "Livros";
}

<h2>Livros</h2>

<p>
    @Html.ActionLink("Adicionar novo livro", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Autor.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataPublicacao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Autor.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @item.DataPublicacao.ToString("dd/MM/yyyy")
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.ID }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Livraria/HBsis/HBsis.Livraria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Livraria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Livraria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- <li>@Html.ActionLink("Início", "Index", "Home")</li> -->
                    <li>@Html.ActionLink("Autor", "Index", "Autor")</li>
                    <li>@Html.ActionLink("Livro", "Index", "Livros")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HBSIS / C6 Consulting</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>